CREATE DATABASE IF NOT EXISTS '${MYSQL_DATABASE}';

USE '${MYSQL_DATABASE}';

CREATE TABLE IF NOT EXISTS task (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE task;
